#version of docker-compose
version: "3.9"

#services
services:
  backend: # name of services that we need
    build: . # find Dockerfile DIR
    container_name: backend # set container_name
    ports:
      - "8000:8000" # map porting <sys port>:<container port>
    command: python manage.py runserver 0.0.0.0:8000 
    # set many command with && sign
    volumes:
      - ./core/:/app
    environment:
      - SECRET_KEY=test
      - DEBUG=True
  smtp4dev:
      image: rnwood/smtp4dev:v3
      restart: always
      ports:
        # Change the number before : to the port the web interface should be accessible on
        - '5000:80'
        # Change the number before : to the port the SMTP server should be accessible on
        - '25:25'
        # Change the number before : to the port the IMAP server should be accessible on
        - '143:143'
      volumes:
        # This is where smtp4dev stores the database..
          - smtp4dev-data:/smtp4dev
      environment:
        - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data:     

# docker-compose up --build