version: "3.9"

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    # command: python manage.py runserver 0.0.0.0:8000
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False
    depends_on:
      - redis

  nginx:
    image: nginx
    container_name: nginx
    ports: 
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - redis
      - backend

    

  worker:
    build: .
    command: celery -A core worker -l INFO
    depends_on:
      - redis
      - backend
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
    - SECRET_KEY=mysupersecretkey
    - DEBUG=True
  
volumes:
  static_volume:
  media_volume: